FiorelloMVC/FiorelloMVC/Controllers/BlogDetailController.cs
using FiorelloMVC.Models;
using FiorelloMVC.Services;
using FiorelloMVC.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace FiorelloMVC.Controllers
{
    public class BlogDetailController : Controller
    {
        private readonly IBlogService _blogService;
        public BlogDetailController(IBlogService blogService)
        {
            _blogService = blogService;
        }
        public async Task<IActionResult> Index(int?id)
        {
            if (id is null) return BadRequest();
            Blog blog = await _blogService.GetByIdAsync((int)id);
            if (blog == null) return NotFound();
            return View(blog);
           
        }
    }
}

FiorelloMVC/FiorelloMVC/ViewComponents/FooterViewComponent.cs
using FiorelloMVC.Models;
using FiorelloMVC.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace FiorelloMVC.ViewComponents
{
    public class FooterViewComponent:ViewComponent
    {
        private readonly ISocialMediaService _socialMediaService;
        private readonly ISettingService _settingService;
        public FooterViewComponent(ISocialMediaService socialMediaService, ISettingService settingService)
        {
            _socialMediaService = socialMediaService;
            _settingService = settingService;   
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var datas = new FooterVMVC
            {
                SocialMedias=await _socialMediaService.GetAllAsync(),
                Settings=await _settingService.GetAllAsync(),
            };

            return View(datas);
        }
    }
    public class FooterVMVC
    {
        public IEnumerable<SocialMedia> SocialMedias { get; set; }
        public IDictionary<string,string> Settings { get; set; }
    }
  
}

FiorelloMVC/FiorelloMVC/ViewComponents/HeaderViewComponent.cs
using FiorelloMVC.Services;
using FiorelloMVC.Services.Interfaces;
using FiorelloMVC.ViewModels.Baskets;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace FiorelloMVC.ViewComponents
{
    public class HeaderViewComponent:ViewComponent
    {
        private readonly ISettingService _settingService;
       private readonly IHttpContextAccessor _accessor;
        public HeaderViewComponent(ISettingService settingService, IHttpContextAccessor accessor)
        {
            _settingService = settingService;
            _accessor = accessor;

        }
        public async Task<IViewComponentResult> InvokeAsync()
        {

            List<BasketVM> basketDatas = new();
            if (_accessor.HttpContext.Request.Cookies["basket"] is not null)
            {
                basketDatas = JsonConvert.DeserializeObject<List<BasketVM>>(_accessor.HttpContext.Request.Cookies["basket"]);
            }
            
            Dictionary<string,string>settings=await _settingService.GetAllAsync();

            HeaderVM response = new()
            {
                Settings = settings,
                BasketCount=basketDatas.Sum(m=>m.Count),
                BasketTotalPrice=basketDatas.Sum(m=>m.Count * m.Price),    
                

            };
            return await Task.FromResult(View(response));
        }

    }
    public class HeaderVM
    {
        public int BasketCount { get; set; }
        public decimal BasketTotalPrice { get; set; }
        public Dictionary<string,string> Settings { get; set; }
    }
}

FiorelloMVC/FiorelloMVC/Views/Shared/_BlogPartial.cshtml
@model IEnumerable<BlogVM>
<div class="row pb-5">
    @foreach (var item in Model)
    {

        <div class="col-md-6 col-lg-4">
            <div class="item">
                <div class="img position-relative">
                    <a asp-controller="BlogDetail" asp-action="Index" asp-route-id="@item.Id">

                    <img src="~/img/@item.Image" class="img-fluid" alt="">
                    </a>
                    <div class="date rounded bg-light position-absolute py-1 px-2">
                        <span>@item.CreatedDate</span>
                    </div>
                </div>
                <div class="text mt-3 text-center px-5">
                    <h5>@item.Title</h5>
                    <p class="text-black-50">@item.Description</p>
                </div>
            </div>
        </div>

    }
</div>

FiorelloMVC/FiorelloMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="icon" href="~/img/favicon.png" sizes="192x192" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="~/owlcarousel/owl.carousel.min.css">
    <link rel="stylesheet" href="~/owlcarousel/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/css/style.css">
    @RenderSection("css",required:false)
    <title>Fiorello &#8211; A Flower Shop and Florist WooCommerce Theme</title>
</head>

<body>

    <!-- HEADER START -->

    @await Component.InvokeAsync("Header");
    <!-- HEADER END -->
            @RenderBody()

     @await Component.InvokeAsync("Footer");  


    <!-- FOOTER END -->

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/e5e249fce2.js" crossorigin="anonymous"></script>
    <script src="~/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/js/basket.js"></script>
    <script src="~/js/script.js"></script>
</body>

</html>